# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Analyze repository
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

#     - uses: actions/checkout@v2
#       with:
#         repository: BernieWhite/Rules.BernieWhite
#         path: .ps-rule/private/

    - name: Run PSRule analysis
      uses: microsoft/ps-rule@main
      with:
        modules: PSRule.Rules.Azure

    - name: Run export templates
      run: Install-Module PSRule.Rules.Azure -Force; Get-AzRuleTemplateLink | Export-AzTemplateRuleData -OutputPath out/templates/;
      shell: pwsh

    - name: Run PSRule analysis
      uses: microsoft/ps-rule@main
      with:
        inputType: inputPath
        inputPath: out/templates/
        modules: PSRule.Rules.Azure,PSRule.Rules.CAF
        prerelease: true

    - name: Update build number
      run: |
        gh pr edit ${{ github.event.pull_request.id }} --title ${{ github.event.pull_request.title }} '${{ github.run_id }}''
