
name: Pre-Release

on:
  pull_request:
    types:
      - closed

jobs:
  dev:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.milestone.title, 'v') && github.event.pull_request.merged }}
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - run: |
        gh release create ${{ github.event.pull_request.milestone.title }} --generate-notes --target ${{ github.base_ref }}
