
name: Release

on:
  push:
    branches:
    - main
    tags:
    - 'v1.*'

jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - run: echo 'Hello DEV'

  stable:
    name: Stable
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-B') }}
    steps:
    - run: echo 'Hello STABLE'

  prerelease:
    name: Pre-release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-B') }}
    steps:
    - run: echo 'Hello PRERELEASE'
